### ISSUE TITLE
ppo中的loss_entropy方向应为最大化

### ISSUE THREAD

**Issue by tangzk** [zhangchuheng123/Reinforcement-Implementation#2]
在PPO算法实现中，`https://github.com/zhangchuheng123/Reinforcement-Implementation/blob/master/code/ppo.py`

```total_loss = loss_surr + args.loss_coeff_value * loss_value + args.loss_coeff_entropy * loss_entropy```

所定义的`total_loss`中，`loss_entropy`的方向是否应该为负？即最大化entropy。

**Comment by chenhang98** [comment]
`loss_entropy = torch.mean(torch.exp(minibatch_newlogproba) * minibatch_newlogproba)`
作者这个loss_entropy实际上是-entropy

**Comment by tangzk** [comment]
yes
